import type { Puzzle } from './types'
import { joinLines as j } from './types'

export const ZONE0_PUZZLES: Puzzle[] = [
  {
    id: 'z0-class',
    kind: 'output',
    title: 'Blueprint Hall',
    prompt: 'How many Dog objects does main create?',
    code: j([
      'class Dog {',
      '    String name;',
      '    Dog(String name) { this.name = name; }',
      '}',
      '',
      'public class Count {',
      '    public static void main(String[] args) {',
      '        Dog a = new Dog("Rex");',
      '        Dog b = new Dog("Fido");',
      '        Dog c = a;',
      '        System.out.println(a.name + " " + b.name + " " + c.name);',
      '    }',
      '}',
    ]),
    choices: [
      { id: 'a', label: 'Rex Fido Rex' },
      { id: 'b', label: 'Rex Fido Fido' },
      { id: 'c', label: 'three Dog classes' },
      { id: 'd', label: 'Compile error' },
    ],
    correctId: 'a',
    hint: 'c = a copies the reference, not a third object.',
    explanation:
      'new Dog creates an object. There are two new calls, so two objects. c points at the same object as a, so c.name is also Rex.',
    explanationSteps: [
      'new Dog("Rex") creates object #1.',
      'new Dog("Fido") creates object #2.',
      'c = a makes c refer to object #1.',
      'Print: Rex Fido Rex.',
    ],
    codexId: 'z0',
    expectCompile: 'ok',
    expectedOutput: 'Rex Fido Rex',
    commonTrap: 'Counting three objects because there are three variables.',
  },
  {
    id: 'z0-fields',
    kind: 'output',
    title: 'State Chamber',
    prompt: 'What does main print?',
    code: j([
      'class Counter {',
      '    int n;',
      '    void bump() { n = n + 1; }',
      '    int value() { return n; }',
      '}',
      '',
      'public class Fields {',
      '    public static void main(String[] args) {',
      '        Counter c = new Counter();',
      '        c.bump();',
      '        c.bump();',
      '        System.out.println(c.value());',
      '    }',
      '}',
    ]),
    choices: [
      { id: 'a', label: '0' },
      { id: 'b', label: '1' },
      { id: 'c', label: '2' },
      { id: 'd', label: 'Compile error: n not initialized' },
    ],
    correctId: 'c',
    hint: 'int fields default to 0. bump runs twice.',
    explanation:
      'Fields get default values (0 for int). Each bump adds 1. After two bumps, value() returns 2. Local variables need explicit init; instance fields do not.',
    explanationSteps: [
      'new Counter() leaves n at 0.',
      'First bump → n = 1.',
      'Second bump → n = 2.',
      'value() prints 2.',
    ],
    codexId: 'z0',
    expectCompile: 'ok',
    expectedOutput: '2',
    commonTrap: 'Expecting a compile error because n was not assigned in the constructor.',
  },
  {
    id: 'z0-ctor',
    kind: 'output',
    title: 'First Breath',
    prompt: 'What prints when the object is constructed?',
    code: j([
      'class Torch {',
      '    Torch() {',
      '        System.out.println("lit");',
      '    }',
      '}',
      '',
      'public class Breath {',
      '    public static void main(String[] args) {',
      '        new Torch();',
      '        System.out.println("done");',
      '    }',
      '}',
    ]),
    choices: [
      { id: 'a', label: 'done\nlit' },
      { id: 'b', label: 'lit\ndone' },
      { id: 'c', label: 'lit' },
      { id: 'd', label: 'done' },
    ],
    correctId: 'b',
    hint: 'The constructor body runs as part of new, before new finishes.',
    explanation:
      'new Torch() runs Torch() which prints lit, then control returns to main which prints done.',
    explanationSteps: [
      'Enter new Torch().',
      'Constructor prints lit.',
      'new completes; main continues.',
      'main prints done.',
    ],
    codexId: 'z0',
    expectCompile: 'ok',
    expectedOutput: 'lit\ndone',
    commonTrap: 'Thinking the constructor runs after main finishes.',
  },
  {
    id: 'z0-encap',
    kind: 'compile_error',
    title: 'Private Vault',
    prompt: 'Why does this fail to compile?',
    code: j([
      'class Purse {',
      '    private int coins = 5;',
      '}',
      '',
      'public class Thief {',
      '    public static void main(String[] args) {',
      '        Purse p = new Purse();',
      '        System.out.println(p.coins);',
      '    }',
      '}',
    ]),
    choices: [
      {
        id: 'a',
        label: 'coins is private — Thief cannot read p.coins; use a getter in Purse.',
      },
      { id: 'b', label: 'Purse must be public.' },
      { id: 'c', label: 'private fields cannot be initialized.' },
      { id: 'd', label: 'main cannot create Purse.' },
    ],
    correctId: 'a',
    hint: 'private means only Purse (and its nest) can touch coins.',
    explanation:
      'Encapsulation hides representation. Outside code should call something like int coins() { return coins; } instead of reading the field directly.',
    explanationSteps: [
      'coins is private in Purse.',
      'Thief is a different top-level class.',
      'p.coins is illegal.',
      'Add a public/package getter to expose the value safely.',
    ],
    codexId: 'z0',
    expectCompile: 'fail',
    commonTrap: 'Thinking private only hides from other packages, not other classes in the same file/package.',
  },
  {
    id: 'z0-isa',
    kind: 'output',
    title: 'Is / Has Fork',
    prompt: 'Which print describes the relationships correctly?',
    code: j([
      'class Engine {',
      '    String label() { return "engine"; }',
      '}',
      '',
      'class Car {',
      '    private Engine engine = new Engine();',
      '    String part() { return engine.label(); }',
      '}',
      '',
      'class SportsCar extends Car {}',
      '',
      'public class Fork {',
      '    public static void main(String[] args) {',
      '        SportsCar s = new SportsCar();',
      '        System.out.println(s.part());',
      '        System.out.println(s instanceof Car);',
      '    }',
      '}',
    ]),
    choices: [
      { id: 'a', label: 'engine\ntrue' },
      { id: 'b', label: 'engine\nfalse' },
      { id: 'c', label: 'Compile error' },
      { id: 'd', label: 'true\nengine' },
    ],
    correctId: 'a',
    hint: 'Car HAS-A Engine. SportsCar IS-A Car.',
    explanation:
      'SportsCar inherits part(), which delegates to the Engine field (composition). instanceof Car is true because of inheritance.',
    explanationSteps: [
      'SportsCar extends Car → IS-A Car.',
      'Car holds Engine → HAS-A.',
      'part() returns engine.',
      'instanceof Car prints true.',
    ],
    codexId: 'z0',
    expectCompile: 'ok',
    expectedOutput: 'engine\ntrue',
    commonTrap: 'Calling Engine an IS-A of Car, or expecting instanceof false.',
  },
  {
    id: 'z0-boss',
    kind: 'fix',
    title: 'Foundation Seal',
    prompt: 'Which class sketch is legal Java and encapsulates the name?',
    code: j(['/*FIX*/']),
    choices: [
      {
        id: 'a',
        label: j([
          'class Hero {',
          '    public String name;',
          '}',
        ]),
      },
      {
        id: 'b',
        label: j([
          'class Hero {',
          '    private String name;',
          '    Hero(String name) { this.name = name; }',
          '    String name() { return name; }',
          '}',
        ]),
      },
      {
        id: 'c',
        label: j([
          'class Hero {',
          '    private String name;',
          '    Hero(String name) { name = name; }',
          '}',
        ]),
      },
      {
        id: 'd',
        label: j([
          'class Hero extends String {',
          '    Hero() {}',
          '}',
        ]),
      },
    ],
    correctId: 'b',
    hint: 'Need private field, this.name = name, and a reader. String is final — cannot extend it.',
    explanation:
      'b hides the field, assigns with this.name, and exposes a getter. a is legal but not encapsulated. c’s name = name only touches the parameter. d cannot extend final String.',
    explanationSteps: [
      'Encapsulation wants private + controlled access.',
      'Constructor must assign this.name.',
      'String is final — extends String fails.',
      'b is the complete legal sketch.',
    ],
    codexId: 'z0',
    expectCompile: 'fail',
    fixMode: 'inject',
    fixMarker: '/*FIX*/',
    commonTrap: 'Picking public fields, or forgetting this. in the constructor.',
  },
]
