import type { Puzzle } from './types'
import { joinLines as j } from './types'

export const ZONE8_PUZZLES: Puzzle[] = [
  {
    id: 'z8-compose',
    kind: 'output',
    title: 'HAS-A Bay',
    prompt: 'What does main print?',
    code: j([
      'class Engine {',
      '    void ignite() { System.out.println("vroom"); }',
      '}',
      '',
      'class Car {',
      '    private final Engine engine = new Engine();',
      '    void start() { engine.ignite(); }',
      '}',
      '',
      'public class Bay {',
      '    public static void main(String[] args) {',
      '        new Car().start();',
      '    }',
      '}',
    ]),
    choices: [
      { id: 'a', label: 'vroom' },
      { id: 'b', label: 'Compile error: Car must extend Engine' },
      { id: 'c', label: '(no output)' },
      { id: 'd', label: 'NullPointerException' },
    ],
    correctId: 'a',
    hint: 'Car HAS-A Engine and delegates start() to ignite().',
    explanation:
      'Composition: Car holds an Engine and forwards start() to it. No inheritance is required.',
    explanationSteps: [
      'Car constructs an Engine field.',
      'start() calls engine.ignite().',
      'Prints vroom.',
    ],
    codexId: 'z8',
    expectCompile: 'ok',
    expectedOutput: 'vroom',
    wrongReasons: {
      b: '“Compile error: Car must extend Engine” is incorrect. Car HAS-A Engine and delegates start() to ignite().',
      c: '“(no output)” is incorrect. Car HAS-A Engine and delegates start() to ignite().',
      d: '“NullPointerException” is incorrect. Car HAS-A Engine and delegates start() to ignite().',
    },
    commonTrap: 'Believing Car must extend Engine to use it.',
  },
  {
    id: 'z8-wrong',
    kind: 'concept',
    title: 'False Heir',
    prompt:
      'Stack extends ArrayList only to reuse add/get. Why is that usually the wrong model?',
    code: j([
      'import java.util.ArrayList;',
      '',
      'class Stack extends ArrayList<String> {}',
      '',
      'public class False {',
      '    public static void main(String[] args) {',
      '        System.out.println("isa?");',
      '    }',
      '}',
    ]),
    choices: [
      {
        id: 'a',
        label:
          'A stack is not a true IS-A list — clients can call list methods that break stack rules. Prefer composition.',
      },
      {
        id: 'b',
        label: 'You can never extend ArrayList.',
      },
      {
        id: 'c',
        label: 'Inheritance is always better than composition.',
      },
      {
        id: 'd',
        label: 'Stack must be an interface.',
      },
    ],
    correctId: 'a',
    hint: 'IS-A should mean you can safely substitute the subtype anywhere the parent is expected.',
    explanation:
      'If Stack extends ArrayList, callers can remove(index) or add at arbitrary indexes — not stack behavior. Hold a private List (or Deque) and expose only push/pop.',
    explanationSteps: [
      'Inheritance advertises IS-A.',
      'Stack users inherit the full List API.',
      'That violates stack discipline.',
      'Compose instead of extend.',
    ],
    codexId: 'z8',
    expectCompile: 'ok',
    wrongReasons: {
      b: '“You can never extend ArrayList.” is incorrect. IS-A should mean you can safely substitute the subtype anywhere the parent is expected.',
      c: '“Inheritance is always better than composition.” is incorrect. IS-A should mean you can safely substitute the subtype anywhere the parent is expected.',
      d: '“Stack must be an interface.” is incorrect. IS-A should mean you can safely substitute the subtype anywhere the parent is expected.',
    },
    commonTrap: 'Extending a library class just to reuse a few methods.',
  },
  {
    id: 'z8-delegate',
    kind: 'output',
    title: 'Forward Desk',
    prompt: 'What does main print?',
    code: j([
      'class Logger {',
      '    void log(String m) { System.out.println("log:" + m); }',
      '}',
      '',
      'class Service {',
      '    private final Logger logger = new Logger();',
      '    void serve() { logger.log("ok"); }',
      '}',
      '',
      'public class Desk {',
      '    public static void main(String[] args) {',
      '        new Service().serve();',
      '    }',
      '}',
    ]),
    choices: [
      { id: 'a', label: 'ok' },
      { id: 'b', label: 'log:ok' },
      { id: 'c', label: 'Compile error' },
      { id: 'd', label: 'log:' },
    ],
    correctId: 'b',
    hint: 'Delegation forwards the call to the composed Logger.',
    explanation:
      'Service does not inherit Logger; it owns one and forwards serve() to log(). That is delegation via composition.',
    explanationSteps: [
      'serve() calls logger.log("ok").',
      'Logger prints log:ok.',
    ],
    codexId: 'z8',
    expectCompile: 'ok',
    expectedOutput: 'log:ok',
    wrongReasons: {
      a: '“ok” is incorrect. Delegation forwards the call to the composed Logger.',
      c: '“Compile error” is incorrect. Delegation forwards the call to the composed Logger.',
      d: '“log:” is incorrect. Delegation forwards the call to the composed Logger.',
    },
    commonTrap: 'Expecting Service to extend Logger for this to compile.',
  },
  {
    id: 'z8-raw',
    kind: 'output',
    title: 'Raw List',
    prompt: 'What does main print? (unchecked warnings possible)',
    code: j([
      'import java.util.ArrayList;',
      'import java.util.List;',
      '',
      'public class Raw {',
      '    public static void main(String[] args) {',
      '        List raw = new ArrayList();',
      '        raw.add("hi");',
      '        raw.add(7);',
      '        System.out.println(raw.size());',
      '    }',
      '}',
    ]),
    choices: [
      { id: 'a', label: 'Compile error on add(7)' },
      { id: 'b', label: '2' },
      { id: 'c', label: '1' },
      { id: 'd', label: 'ClassCastException' },
    ],
    correctId: 'b',
    hint: 'Raw List skips element-type checks at compile time; both adds succeed.',
    explanation:
      'A raw List accepts any Object. You get unchecked warnings, but size is 2. List<String> would reject add(7) at compile time — that is why parameterized types are safer.',
    explanationSteps: [
      'raw is a raw ArrayList.',
      'add("hi") and add(7) both compile (with warnings).',
      'size() is 2.',
    ],
    codexId: 'z8',
    expectCompile: 'ok',
    expectedOutput: '2',
    wrongReasons: {
      a: '“Compile error on add(7)” is incorrect. Raw List skips element-type checks at compile time; both adds succeed.',
      c: '“1” is incorrect. Raw List skips element-type checks at compile time; both adds succeed.',
      d: '“ClassCastException” is incorrect. Raw List skips element-type checks at compile time; both adds succeed.',
    },
    commonTrap: 'Thinking add(7) is a hard compile error on a raw List.',
  },
  {
    id: 'z8-diamond',
    kind: 'output',
    title: 'Diamond Tip',
    prompt: 'What does main print?',
    code: j([
      'import java.util.ArrayList;',
      'import java.util.List;',
      '',
      'public class Tip {',
      '    public static void main(String[] args) {',
      '        List<String> words = new ArrayList<>();',
      '        words.add("oop");',
      '        System.out.println(words.get(0));',
      '    }',
      '}',
    ]),
    choices: [
      { id: 'a', label: 'oop' },
      { id: 'b', label: 'Compile error: missing type on right' },
      { id: 'c', label: 'null' },
      { id: 'd', label: 'ArrayList' },
    ],
    correctId: 'a',
    hint: '<> is the diamond operator — the compiler infers ArrayList<String>.',
    explanation:
      'Since Java 7, new ArrayList<>() infers the type argument from the left-hand side List<String>. The list holds "oop".',
    explanationSteps: [
      'Target type is List<String>.',
      'Diamond infers ArrayList<String>.',
      'get(0) returns oop.',
    ],
    codexId: 'z8',
    expectCompile: 'ok',
    expectedOutput: 'oop',
    wrongReasons: {
      b: '“Compile error: missing type on right” is incorrect. <> is the diamond operator — the compiler infers ArrayList<String>.',
      c: '“null” is incorrect. <> is the diamond operator — the compiler infers ArrayList<String>.',
      d: '“ArrayList” is incorrect. <> is the diamond operator — the compiler infers ArrayList<String>.',
    },
    commonTrap: 'Believing you must repeat <String> on the right-hand side.',
  },
  {
    id: 'z8-boss',
    kind: 'fix',
    title: 'Yard Seal',
    prompt:
      'Replace inheritance with composition. Which Stack body is the better design?',
    code: j([
      'import java.util.ArrayDeque;',
      'import java.util.Deque;',
      '',
      'class Stack {',
      '    /*FIX*/',
      '}',
      '',
      'public class Yard {',
      '    public static void main(String[] args) {',
      '        Stack s = new Stack();',
      '        s.push("a");',
      '        System.out.println(s.pop());',
      '    }',
      '}',
    ]),
    choices: [
      {
        id: 'a',
        label: j([
          'extends ArrayList<String> {',
          '    void push(String x) { add(x); }',
          '    String pop() { return remove(size() - 1); }',
          '}',
        ]),
      },
      {
        id: 'b',
        label: j([
          'private final Deque<String> q = new ArrayDeque<>();',
          '    void push(String x) { q.push(x); }',
          '    String pop() { return q.pop(); }',
        ]),
      },
      {
        id: 'c',
        label: j([
          'public String[] data;',
          '    void push(String x) {}',
          '    String pop() { return null; }',
        ]),
      },
      {
        id: 'd',
        label: 'implements Deque<String> {}',
      },
    ],
    correctId: 'b',
    hint: 'Hide a Deque and expose only push/pop.',
    explanation:
      'b composes a Deque and delegates. a still IS-A List with all list methods. c is incomplete. d forces implementing a huge interface.',
    explanationSteps: [
      'Inject b into class Stack.',
      'push/pop delegate to ArrayDeque.',
      'main prints a.',
      'Composition keeps the API minimal.',
    ],
    codexId: 'z8',
    expectCompile: 'fail',
    fixMode: 'inject',
    fixMarker: '/*FIX*/',
    wrongReasons: {
      a: 'Extending ArrayList still exposes the full List API — that is inheritance, not a minimal stack.',
      c: 'An incomplete public array with empty methods is not a composed stack.',
      d: 'Implementing Deque forces a huge surface area; prefer a private Deque field.',
    },
    commonTrap: 'Extending ArrayList and calling it a stack.',
  },
]
