import type { Puzzle } from './types'
import { joinLines as j } from './types'

export const ZONE4_PUZZLES: Puzzle[] = [
  {
    id: 'z4-default',
    kind: 'output',
    title: 'Default Spark',
    prompt: 'Wizard is empty. What does new Wizard().cast() print?',
    code: j([
      'interface Spell {',
      '    default void cast() {',
      '        System.out.println("spark");',
      '    }',
      '}',
      '',
      'class Wizard implements Spell {}',
      '',
      'public class Spark {',
      '    public static void main(String[] args) {',
      '        new Wizard().cast();',
      '    }',
      '}',
    ]),
    choices: [
      { id: 'a', label: 'Compile error: Wizard must implement cast' },
      { id: 'b', label: 'spark' },
      { id: 'c', label: 'Compile error: interfaces cannot have bodies' },
      { id: 'd', label: '(prints nothing)' },
    ],
    correctId: 'b',
    hint: 'default methods are inherited by implementing classes unless they override them.',
    explanation:
      'Since Java 8, an interface may supply an instance method body with default. Wizard implements Spell and does not override cast, so it inherits the default. new Wizard().cast() prints spark. The class does not need an empty stub.',
    explanationSteps: [
      'Spell.cast is a default instance method.',
      'Wizard implements Spell and does not declare cast.',
      'Wizard inherits the default implementation.',
      'The call prints spark.',
    ],
    codexId: 'default-methods',
    expectCompile: 'ok',
    expectedOutput: 'spark',
    commonTrap: 'Insisting Wizard is abstract or that it must write its own cast().',
  },
  {
    id: 'z4-static',
    kind: 'compile_error',
    title: 'Static Altar',
    prompt: 'Why does this fail to compile?',
    code: j([
      'interface Spell {',
      '    static void sage() {',
      '        System.out.println("sage");',
      '    }',
      '}',
      '',
      'class Wizard implements Spell {}',
      '',
      'public class Altar {',
      '    public static void main(String[] args) {',
      '        Wizard w = new Wizard();',
      '        w.sage();',
      '    }',
      '}',
    ]),
    choices: [
      {
        id: 'a',
        label:
          'Interface static methods are not inherited. Call Spell.sage() — not w.sage() or Wizard.sage().',
      },
      {
        id: 'b',
        label: 'static methods are illegal in interfaces.',
      },
      {
        id: 'c',
        label: 'sage() must be default, not static.',
      },
      {
        id: 'd',
        label: 'Wizard must override sage() to use it.',
      },
    ],
    correctId: 'a',
    hint: 'Class static methods can be mentioned on a subclass. Interface static methods cannot.',
    explanation:
      'A static method in an interface is a member of the interface type only. Implementing the interface does not put sage into Wizard’s namespace. The legal call is Spell.sage(). Instance syntax w.sage() is also illegal. This is unlike Parent.staticMethod() inherited by Child.',
    explanationSteps: [
      'Spell.sage is static on the interface.',
      'Wizard implements Spell but does not inherit static interface methods.',
      'w.sage() looks for sage on Wizard/Object — not found.',
      'Spell.sage() would compile and print sage.',
    ],
    codexId: 'interface-static',
    expectCompile: 'fail',
    commonTrap: 'Calling Wizard.sage() as if class-static inheritance applied.',
  },
  {
    id: 'z4-diamond',
    kind: 'compile_error',
    title: 'Diamond Split',
    prompt: 'Why does class C fail to compile?',
    code: j([
      'interface A {',
      '    default void m() {',
      '        System.out.println("A");',
      '    }',
      '}',
      '',
      'interface B {',
      '    default void m() {',
      '        System.out.println("B");',
      '    }',
      '}',
      '',
      'class C implements A, B {}',
    ]),
    choices: [
      {
        id: 'a',
        label:
          'A and B both provide default m(). C must override m() and may call A.super.m() or B.super.m().',
      },
      {
        id: 'b',
        label: 'A class cannot implement two interfaces.',
      },
      {
        id: 'c',
        label: 'The compiler silently picks A because it is listed first.',
      },
      {
        id: 'd',
        label: 'default methods cannot share a name even in unrelated interfaces.',
      },
    ],
    correctId: 'a',
    hint: 'Two concrete defaults with the same signature is a conflict. Abstract + default is not.',
    explanation:
      'When two superinterfaces supply a default method with the same signature, the implementing class must override it. There is no “first listed wins.” Inside the override you disambiguate with InterfaceName.super.m(). If one side were abstract void m() and the other default void m(), the default would win and C would compile without an override.',
    explanationSteps: [
      'A.m and B.m are both default, same signature.',
      'C inherits two concrete methods and does not override — compile error.',
      'Adding public void m() { A.super.m(); } would fix it.',
      'super.m() without the interface name is not enough here (C has no superclass m).',
    ],
    codexId: 'diamond',
    expectCompile: 'fail',
    commonTrap: 'Assuming the compiler picks A or B automatically.',
  },
  {
    id: 'z4-super',
    kind: 'output',
    title: 'Named Super',
    prompt: 'C resolves the diamond. What does new C().m() print?',
    code: j([
      'interface A {',
      '    default void m() {',
      '        System.out.println("A");',
      '    }',
      '}',
      '',
      'interface B {',
      '    default void m() {',
      '        System.out.println("B");',
      '    }',
      '}',
      '',
      'class C implements A, B {',
      '    public void m() {',
      '        A.super.m();',
      '        System.out.println("C");',
      '    }',
      '}',
      '',
      'public class Named {',
      '    public static void main(String[] args) {',
      '        new C().m();',
      '    }',
      '}',
    ]),
    choices: [
      { id: 'a', label: 'B\nC' },
      { id: 'b', label: 'A\nC' },
      { id: 'c', label: 'A\nB\nC' },
      { id: 'd', label: 'C' },
    ],
    correctId: 'b',
    hint: 'A.super.m() is an explicit call to A’s default. B’s default is not invoked.',
    explanation:
      'The override in C is required to compile. A.super.m() is the Java 8 syntax for invoking a specific interface default. It prints A, then C prints C. B.super.m() was not called.',
    explanationSteps: [
      'C.m is the method that actually runs.',
      'A.super.m() executes A’s default body — prints A.',
      'Then C prints C.',
      'B’s default is unused in this body.',
    ],
    codexId: 'diamond',
    expectCompile: 'ok',
    expectedOutput: 'A\nC',
    commonTrap: 'Printing both A and B, or thinking A.super.m() is illegal outside a class-superclass.',
  },
  {
    id: 'z4-field',
    kind: 'compile_error',
    title: 'Constant Well',
    prompt: 'Why does this fail to compile?',
    code: j([
      'interface Runes {',
      '    int X = 1;',
      '}',
      '',
      'public class Well {',
      '    public static void main(String[] args) {',
      '        Runes.X++;',
      '        System.out.println(Runes.X);',
      '    }',
      '}',
    ]),
    choices: [
      {
        id: 'a',
        label:
          'Interface fields are implicitly public static final. Runes.X is a constant; ++ is an assignment.',
      },
      {
        id: 'b',
        label: 'X is private because interface fields are private by default.',
      },
      {
        id: 'c',
        label: 'You must write Runes.X = Runes.X + 1; instead of ++.',
      },
      {
        id: 'd',
        label: 'main cannot mention interface names.',
      },
    ],
    correctId: 'a',
    hint: 'int X = 1 in an interface is public static final int X = 1.',
    explanation:
      'Every field declared in an interface is public, static, and final, even if you write none of those keywords. Runes.X++ tries to assign to a final variable. System.out.println(Runes.X) alone would compile and print 1. There is no per-instance copy of X on implementers.',
    explanationSteps: [
      'int X = 1 is public static final int X = 1.',
      '++ needs a writable variable.',
      'Final constants are not writable.',
      'The program does not compile.',
    ],
    codexId: 'interface-fields',
    expectCompile: 'fail',
    commonTrap: 'Treating X as a mutable static or as an instance field of implementers.',
  },
  {
    id: 'z4-boss',
    kind: 'compile_error',
    title: 'Nexus Core',
    prompt:
      'Cat supplies a default roar(). Beast still declares roar() abstract. Why is Lion illegal?',
    code: j([
      'abstract class Beast {',
      '    abstract void roar();',
      '}',
      '',
      'interface Cat {',
      '    default void roar() {',
      '        System.out.println("meow");',
      '    }',
      '}',
      '',
      'class Lion extends Beast implements Cat {}',
    ]),
    choices: [
      {
        id: 'a',
        label:
          'An interface default does not implement a superclass abstract method. Lion must write roar() (or stay abstract).',
      },
      {
        id: 'b',
        label: 'A class cannot extend a class and implement an interface at the same time.',
      },
      {
        id: 'c',
        label: 'default roar() conflicts with abstract roar() the same way two defaults do, so Lion must pick Cat.super.roar().',
      },
      {
        id: 'd',
        label: 'Beast cannot be abstract if any interface already has roar().',
      },
    ],
    correctId: 'a',
    hint: 'Defaults fill in other interfaces. They do not fill in abstract class methods.',
    explanation:
      'This is the exam distinction. If Speak has abstract say() and Whisper has default say(), a class that implements both inherits the default and compiles. If the abstract method comes from a superclass, the default is ignored for that method: the class still has an unimplemented abstract roar() from Beast. Lion must provide a body or be declared abstract. Class methods always win over interface defaults; an abstract class method still counts as a class method that needs a real implementation in a concrete subclass.',
    explanationSteps: [
      'Lion’s superclass Beast requires roar().',
      'Cat.default roar is an interface method, not a Beast override.',
      'A concrete class cannot leave Beast.roar abstract.',
      'Add public void roar() { ... } or make Lion abstract.',
    ],
    codexId: 'class-vs-default',
    expectCompile: 'fail',
    commonTrap: 'Thinking the default satisfies Beast.roar() the same way it would satisfy another interface.',
  },
]
