import type { Puzzle } from './types'
import { joinLines as j } from './types'

export const ZONE3_PUZZLES: Puzzle[] = [
  {
    id: 'z3-override',
    kind: 'output',
    title: 'True Voice',
    prompt: 'speak is an instance method. What does main print?',
    code: j([
      'class Parent {',
      '    void speak() {',
      '        System.out.println("parent");',
      '    }',
      '}',
      '',
      'class Child extends Parent {',
      '    @Override',
      '    void speak() {',
      '        System.out.println("child");',
      '    }',
      '}',
      '',
      'public class Voice {',
      '    public static void main(String[] args) {',
      '        Parent p = new Child();',
      '        p.speak();',
      '    }',
      '}',
    ]),
    choices: [
      { id: 'a', label: 'parent' },
      { id: 'b', label: 'child' },
      { id: 'c', label: 'parent\nchild' },
      { id: 'd', label: 'Compile error: p is not a Child' },
    ],
    correctId: 'b',
    hint: 'The compiler checks speak on Parent. The JVM runs the version from the object’s class: Child.',
    explanation:
      'This is overriding (dynamic dispatch). Parent p = new Child() is legal. p.speak() is allowed because Parent declares speak. At runtime the object is a Child, so Child.speak() runs.',
    explanationSteps: [
      'The declared type of p is Parent, so only Parent’s API is callable.',
      'Parent has speak(), so the call compiles.',
      'The runtime class is Child, which overrides speak.',
      'The JVM invokes Child.speak() and prints child.',
    ],
    codexId: 'override-dispatch',
    expectCompile: 'ok',
    expectedOutput: 'child',
    wrongReasons: {
      a: '“parent” is incorrect. The compiler checks speak on Parent. The JVM runs the version from the object’s class: Child.',
      c: '“parent\\nchild” is incorrect. The compiler checks speak on Parent. The JVM runs the version from the object’s class: Child.',
      d: '“Compile error: p is not a Child” is incorrect. The compiler checks speak on Parent. The JVM runs the version from the object’s class: Child.',
    },
    commonTrap: 'Printing parent because the variable is typed Parent.',
  },
  {
    id: 'z3-static',
    kind: 'output',
    title: 'Static Mask',
    prompt:
      'speak is static in both classes. What does p.speak() print? (The compiler also warns you to call it on the type.)',
    code: j([
      'class Parent {',
      '    static void speak() {',
      '        System.out.println("parent");',
      '    }',
      '}',
      '',
      'class Child extends Parent {',
      '    static void speak() {',
      '        System.out.println("child");',
      '    }',
      '}',
      '',
      'public class Mask {',
      '    public static void main(String[] args) {',
      '        Parent p = new Child();',
      '        p.speak();',
      '    }',
      '}',
    ]),
    choices: [
      { id: 'a', label: 'child' },
      { id: 'b', label: 'parent' },
      { id: 'c', label: 'parent\nchild' },
      { id: 'd', label: 'Compile error: static methods cannot hide' },
    ],
    correctId: 'b',
    hint: 'static methods hide. The declared type of p is Parent, so Parent.speak() is invoked.',
    explanation:
      'static methods are not dispatched on the runtime object. p.speak() is compiled as Parent.speak() because p’s type is Parent. Child.speak() hides the parent method; it would run only as Child.speak() or on a Child-typed variable. This is hiding, not overriding. @Override would be rejected on a static method that “matches” a parent static method.',
    explanationSteps: [
      'Parent p = new Child() still has compile-time type Parent.',
      'speak is static, so the compiler binds the call to Parent.speak.',
      'The runtime class Child is ignored for this call.',
      'Parent.speak() prints parent.',
    ],
    codexId: 'static-hiding',
    expectCompile: 'ok',
    expectedOutput: 'parent',
    wrongReasons: {
      a: '“child” is incorrect. static methods hide. The declared type of p is Parent, so Parent.speak() is invoked.',
      c: '“parent\\nchild” is incorrect. static methods hide. The declared type of p is Parent, so Parent.speak() is invoked.',
      d: '“Compile error: static methods cannot hide” is incorrect. static methods hide. The declared type of p is Parent, so Parent.speak() is invoked.',
    },
    commonTrap: 'Applying the instance-override rule to a static method and answering child.',
  },
  {
    id: 'z3-field',
    kind: 'output',
    title: 'Field Mirage',
    prompt: 'Child hides x. What do the two prints show?',
    code: j([
      'class Parent {',
      '    int x = 1;',
      '}',
      '',
      'class Child extends Parent {',
      '    int x = 2;',
      '}',
      '',
      'public class Mirage {',
      '    public static void main(String[] args) {',
      '        Parent p = new Child();',
      '        Child c = new Child();',
      '        System.out.println(p.x);',
      '        System.out.println(c.x);',
      '    }',
      '}',
    ]),
    choices: [
      { id: 'a', label: '2\n2' },
      { id: 'b', label: '1\n2' },
      { id: 'c', label: '1\n1' },
      { id: 'd', label: '2\n1' },
    ],
    correctId: 'b',
    hint: 'Field access uses the compile-time type. p is Parent, c is Child.',
    explanation:
      'Fields do not override. Each class has its own x. p.x is Parent.x (1). c.x is Child.x (2). The Child object still contains the Parent.x field; you just cannot see it through a Child-typed expression without a cast to Parent.',
    explanationSteps: [
      'new Child() has both Parent.x = 1 and Child.x = 2.',
      'p has compile-time type Parent, so p.x is 1.',
      'c has compile-time type Child, so c.x is 2.',
      'No dispatch happens; this is hiding.',
    ],
    codexId: 'static-hiding',
    expectCompile: 'ok',
    expectedOutput: '1\n2',
    wrongReasons: {
      a: '“2\\n2” is incorrect. Field access uses the compile-time type. p is Parent, c is Child.',
      c: '“1\\n1” is incorrect. Field access uses the compile-time type. p is Parent, c is Child.',
      d: '“2\\n1” is incorrect. Field access uses the compile-time type. p is Parent, c is Child.',
    },
    commonTrap: 'Printing 2\n2 as if fields overrode like instance methods.',
  },
  {
    id: 'z3-overload',
    kind: 'output',
    title: 'Exact Match',
    prompt: 'Three overloads exist. Which one does m(1) choose?',
    code: j([
      'class Box {',
      '    void m(int n) {',
      '        System.out.println("int");',
      '    }',
      '    void m(long n) {',
      '        System.out.println("long");',
      '    }',
      '    void m(Integer n) {',
      '        System.out.println("Integer");',
      '    }',
      '}',
      '',
      'public class Exact {',
      '    public static void main(String[] args) {',
      '        new Box().m(1);',
      '    }',
      '}',
    ]),
    choices: [
      { id: 'a', label: 'long' },
      { id: 'b', label: 'Integer' },
      { id: 'c', label: 'int' },
      { id: 'd', label: 'Compile error: ambiguous' },
    ],
    correctId: 'c',
    hint: '1 is an int literal. Exact match beats widening and boxing.',
    explanation:
      'Overload resolution is compile-time. An int argument matches m(int) exactly. Widening to long and boxing to Integer are worse conversions, so they are not chosen. The call is not ambiguous.',
    explanationSteps: [
      'The argument 1 has type int.',
      'm(int) is an identity conversion — phase 1 of overload resolution.',
      'm(long) would require widening; m(Integer) would require boxing.',
      'The compiler picks m(int) and prints int.',
    ],
    codexId: 'overload-resolution',
    expectCompile: 'ok',
    expectedOutput: 'int',
    wrongReasons: {
      a: '“long” is incorrect. 1 is an int literal. Exact match beats widening and boxing.',
      b: '“Integer” is incorrect. 1 is an int literal. Exact match beats widening and boxing.',
      d: '“Compile error: ambiguous” is incorrect. 1 is an int literal. Exact match beats widening and boxing.',
    },
    commonTrap: 'Picking Integer because “Java boxes,” or long because “int always widens.”',
  },
  {
    id: 'z3-varargs',
    kind: 'output',
    title: 'Varargs Last',
    prompt: 'There is no m(int). What does m(1) print?',
    code: j([
      'class Box {',
      '    void m(Integer n) {',
      '        System.out.println("Integer");',
      '    }',
      '    void m(int... n) {',
      '        System.out.println("varargs");',
      '    }',
      '}',
      '',
      'public class Last {',
      '    public static void main(String[] args) {',
      '        new Box().m(1);',
      '    }',
      '}',
    ]),
    choices: [
      { id: 'a', label: 'varargs' },
      { id: 'b', label: 'Integer' },
      { id: 'c', label: 'Compile error: ambiguous' },
      { id: 'd', label: 'int' },
    ],
    correctId: 'b',
    hint: 'Boxing is considered before varargs. int → Integer is preferred to int → int[].',
    explanation:
      'Overload resolution has phases: (1) methods without boxing or varargs, (2) boxing/unboxing, (3) varargs. m(int) is absent. Phase 2 finds m(Integer) via boxing. varargs is phase 3, so it loses. The call is not ambiguous.',
    explanationSteps: [
      'No exact m(int) exists.',
      'Phase 2: box 1 to Integer and call m(Integer).',
      'm(int...) is only considered if phase 2 finds nothing.',
      'Output is Integer.',
    ],
    codexId: 'overload-resolution',
    expectCompile: 'ok',
    expectedOutput: 'Integer',
    wrongReasons: {
      a: '“varargs” is incorrect. Boxing is considered before varargs. int → Integer is preferred to int → int[].',
      c: '“Compile error: ambiguous” is incorrect. Boxing is considered before varargs. int → Integer is preferred to int → int[].',
      d: '“int” is incorrect. Boxing is considered before varargs. int → Integer is preferred to int → int[].',
    },
    commonTrap: 'Choosing varargs because 1 can be a one-element int array, or calling the call ambiguous.',
  },
  {
    id: 'z3-boss',
    kind: 'output',
    title: 'Two Clocks',
    prompt:
      'cast is overloaded; act is overridden. Parent p = new Child(). What does mage.cast(p) print?',
    code: j([
      'class Parent {',
      '    void act() {',
      '        System.out.println("P.act");',
      '    }',
      '}',
      '',
      'class Child extends Parent {',
      '    @Override',
      '    void act() {',
      '        System.out.println("C.act");',
      '    }',
      '}',
      '',
      'class Mage {',
      '    void cast(Parent p) {',
      '        System.out.println("cast-parent");',
      '        p.act();',
      '    }',
      '    void cast(Child c) {',
      '        System.out.println("cast-child");',
      '        c.act();',
      '    }',
      '}',
      '',
      'public class Clocks {',
      '    public static void main(String[] args) {',
      '        Mage mage = new Mage();',
      '        Parent p = new Child();',
      '        mage.cast(p);',
      '    }',
      '}',
    ]),
    choices: [
      { id: 'a', label: 'cast-child\nC.act' },
      { id: 'b', label: 'cast-parent\nP.act' },
      { id: 'c', label: 'cast-parent\nC.act' },
      { id: 'd', label: 'cast-child\nP.act' },
    ],
    correctId: 'c',
    hint: 'The overload uses p’s declared type (Parent). Inside that method, p.act() still dispatches.',
    explanation:
      'Two different clocks. Overload resolution looks at the compile-time type of the argument: p is Parent, so cast(Parent) is chosen — even though the object is a Child. Inside cast(Parent), p.act() is an instance call, so Child.act() runs. If the code had been mage.cast((Child) p) or mage.cast(new Child()), the other overload would be chosen.',
    explanationSteps: [
      'p has declared type Parent, so mage.cast(p) binds to cast(Parent).',
      'That method prints cast-parent.',
      'p.act() is an overridable instance method; runtime type is Child.',
      'Child.act() prints C.act.',
    ],
    codexId: 'overload-then-override',
    expectCompile: 'ok',
    expectedOutput: 'cast-parent\nC.act',
    wrongReasons: {
      a: 'Overload uses the declared type Parent, so cast-child is not chosen.',
      b: 'cast-parent is right, but p.act() still overrides to Child — not Parent.act.',
      d: 'Wrong on both clocks: overload is Parent, override is Child.',
    },
    commonTrap: 'Letting the runtime type of p pick cast(Child), or also using Parent.act because p is Parent.',
  },
]
