import type { Puzzle } from './types'
import { joinLines as j } from './types'

export const ZONE5_PUZZLES: Puzzle[] = [
  {
    id: 'z5-final-ref',
    kind: 'output',
    title: 'Frozen Handle',
    prompt:
      'items is final. What does main print? (Would items = new ArrayList<>() compile?)',
    code: j([
      'import java.util.ArrayList;',
      'import java.util.List;',
      '',
      'public class Handle {',
      '    public static void main(String[] args) {',
      '        final List<String> items = new ArrayList<>();',
      '        items.add("rune");',
      '        System.out.println(items.size());',
      '    }',
      '}',
    ]),
    choices: [
      { id: 'a', label: 'Compile error: cannot call add on a final list' },
      { id: 'b', label: '1' },
      { id: 'c', label: '0' },
      { id: 'd', label: 'Compile error: ArrayList is mutable' },
    ],
    correctId: 'b',
    hint: 'final locks the variable, not the object. add mutates the ArrayList. Reassigning items would not compile.',
    explanation:
      'final List<String> items means the reference cannot be retargeted. The ArrayList object remains mutable, so add is legal. items = new ArrayList<>() would be a compile error. Deep immutability needs a type that has no mutators (or an unmodifiable wrapper), plus no leaked aliases.',
    explanationSteps: [
      'items is a final local variable pointing at one ArrayList.',
      'items.add("rune") mutates that object — allowed.',
      'size() is 1.',
      'A later items = new ArrayList<>() would not compile.',
    ],
    codexId: 'final-ref',
    expectCompile: 'ok',
    expectedOutput: '1',
    commonTrap: 'Treating final List as a frozen collection so add would not compile.',
  },
  {
    id: 'z5-final-method',
    kind: 'compile_error',
    title: 'Last Word',
    prompt: 'Why does Ruin fail to compile?',
    code: j([
      'class Keep {',
      '    final void seal() {',
      '        System.out.println("sealed");',
      '    }',
      '}',
      '',
      'class Ruin extends Keep {',
      '    void seal() {',
      '        System.out.println("broken");',
      '    }',
      '}',
    ]),
    choices: [
      {
        id: 'a',
        label: 'final methods cannot be overridden. Ruin.seal() is an illegal override.',
      },
      {
        id: 'b',
        label: 'Keep cannot be subclassed because it has a final method.',
      },
      {
        id: 'c',
        label: 'Ruin must write @Override or the compiler rejects the method.',
      },
      {
        id: 'd',
        label: 'seal() in Keep is private by default, so Ruin cannot mention it.',
      },
    ],
    correctId: 'a',
    hint: 'Subclassing Keep is legal. Replacing seal() is not.',
    explanation:
      'A final instance method is the last implementation. A subclass may still exist and may overload seal with different parameters, but it may not override it. Package-private (no modifier) seal() in Keep is still visible to Ruin in the same package, which is why the compiler treats Ruin.seal() as an attempted override rather than a new method.',
    explanationSteps: [
      'Keep.seal is final and package-visible.',
      'Ruin.seal has the same signature — it would be an override.',
      'Overriding a final method is a compile error.',
      'class Ruin extends Keep {} with no seal() would compile.',
    ],
    codexId: 'final-method',
    expectCompile: 'fail',
    commonTrap: 'Believing a final method makes the whole class final.',
  },
  {
    id: 'z5-hash',
    kind: 'output',
    title: 'Broken Contract',
    prompt:
      'Coin overrides equals but not hashCode. What does contains print for a logically equal coin?',
    code: j([
      'import java.util.HashSet;',
      '',
      'class Coin {',
      '    final int id;',
      '    Coin(int id) {',
      '        this.id = id;',
      '    }',
      '    @Override',
      '    public boolean equals(Object o) {',
      '        if (!(o instanceof Coin)) return false;',
      '        Coin c = (Coin) o;',
      '        return c.id == id;',
      '    }',
      '}',
      '',
      'public class Purse {',
      '    public static void main(String[] args) {',
      '        HashSet<Coin> set = new HashSet<>();',
      '        set.add(new Coin(1));',
      '        System.out.println(set.contains(new Coin(1)));',
      '    }',
      '}',
    ]),
    choices: [
      { id: 'a', label: 'true' },
      { id: 'b', label: 'false' },
      { id: 'c', label: 'Compile error: hashCode is required' },
      { id: 'd', label: 'true\nfalse' },
    ],
    correctId: 'b',
    hint: 'HashSet finds the bucket with hashCode first. Two Coin(1) objects have different identity hashes.',
    explanation:
      'The contract: if a.equals(b) then a.hashCode() == b.hashCode(). Coin.equals is value-based, but hashCode is still Object’s identity hash. HashSet.contains(new Coin(1)) looks in the bucket for that new object’s hash, not the first coin’s bucket, so it returns false even though equals would have been true. The compiler does not require you to override hashCode — it is a logic bug, not a compile error. Fix: hashCode() { return Integer.hashCode(id); }.',
    explanationSteps: [
      'set.add stores the first Coin in the bucket for its identity hashCode.',
      'contains(new Coin(1)) hashes a different object.',
      'The set does not even call equals on the first coin if the buckets differ.',
      'Prints false. Fix: hashCode() { return id; } (consistent with equals).',
    ],
    codexId: 'equals-hashcode',
    expectCompile: 'ok',
    expectedOutput: 'false',
    commonTrap: 'Answering true because equals is overridden, or claiming it does not compile.',
  },
  {
    id: 'z5-equals',
    kind: 'output',
    title: 'One-Way Mirror',
    prompt: 'What does main print for the two equals calls?',
    code: j([
      'class Point {',
      '    int x;',
      '    Point(int x) {',
      '        this.x = x;',
      '    }',
      '    @Override',
      '    public boolean equals(Object o) {',
      '        if (!(o instanceof Point)) return false;',
      '        return ((Point) o).x == x;',
      '    }',
      '}',
      '',
      'class NamedPoint extends Point {',
      '    String n;',
      '    NamedPoint(int x, String n) {',
      '        super(x);',
      '        this.n = n;',
      '    }',
      '    @Override',
      '    public boolean equals(Object o) {',
      '        if (!(o instanceof NamedPoint)) return false;',
      '        NamedPoint other = (NamedPoint) o;',
      '        return super.equals(other) && n.equals(other.n);',
      '    }',
      '}',
      '',
      'public class Mirror {',
      '    public static void main(String[] args) {',
      '        Point p = new Point(1);',
      '        NamedPoint n = new NamedPoint(1, "a");',
      '        System.out.println(p.equals(n) + " " + n.equals(p));',
      '    }',
      '}',
    ]),
    choices: [
      { id: 'a', label: 'true true' },
      { id: 'b', label: 'false false' },
      { id: 'c', label: 'true false' },
      { id: 'd', label: 'false true' },
    ],
    correctId: 'c',
    hint: 'p.equals(n) uses instanceof Point. n.equals(p) requires a NamedPoint.',
    explanation:
      'equals must be symmetric: a.equals(b) iff b.equals(a). Point treats any Point with the same x as equal, so p.equals(n) is true. NamedPoint rejects non-NamedPoint arguments, so n.equals(p) is false. This is why instanceof-based equals plus a subclass that adds fields is an exam favorite. getClass() == o.getClass() restores symmetry (then they are both false).',
    explanationSteps: [
      'p.equals(n): n instanceof Point, x==1 → true.',
      'n.equals(p): p instanceof NamedPoint → false.',
      'The pair is true false — contract broken.',
      'Hash-based collections would also behave oddly if these were mixed as keys.',
    ],
    codexId: 'equals-symmetric',
    expectCompile: 'ok',
    expectedOutput: 'true false',
    commonTrap: 'Answering true true because both have x == 1.',
  },
  {
    id: 'z5-sealed',
    kind: 'compile_error',
    title: 'Sealed Gate',
    prompt:
      'Java 17+. Why does Triangle fail to compile?',
    code: j([
      'sealed class Shape permits Circle, Square {}',
      '',
      'final class Circle extends Shape {}',
      '',
      'final class Square extends Shape {}',
      '',
      'final class Triangle extends Shape {}',
    ]),
    choices: [
      {
        id: 'a',
        label:
          'Triangle is not named in Shape’s permits list, so it may not extend the sealed class.',
      },
      {
        id: 'b',
        label: 'sealed classes cannot have more than two subclasses.',
      },
      {
        id: 'c',
        label: 'Circle and Square must not be final; they must be non-sealed.',
      },
      {
        id: 'd',
        label: 'Shape must be abstract to be sealed.',
      },
    ],
    correctId: 'a',
    hint: 'permits is a closed guest list. Circle and Square are correctly final permitted subtypes.',
    explanation:
      'A sealed class must list every allowed direct subclass in permits. Those subclasses must be final, sealed, or non-sealed. Circle and Square are listed and final — legal. Triangle is a direct subclass that is not permitted — compile error. Shape does not have to be abstract (though it often is). This feature is Java 17+.',
    explanationSteps: [
      'Shape is sealed and permits only Circle and Square.',
      'Circle and Square are final, as required of permitted types that do not continue the seal.',
      'Triangle extends Shape but is not in permits.',
      'The compiler rejects Triangle.',
    ],
    codexId: 'sealed',
    expectCompile: 'fail',
    commonTrap: 'Claiming Circle/Square cannot be final, or that sealed implies abstract.',
  },
  {
    id: 'z5-boss',
    kind: 'fix',
    title: 'Crypt Heart',
    prompt:
      'Which Scroll is actually immutable? (No setters, private final state, no leaked mutable collection.)',
    code: j([
      'import java.util.ArrayList;',
      'import java.util.List;',
      '',
      '/*FIX*/',
    ]),
    choices: [
      {
        id: 'a',
        label: j([
          'class Scroll {',
          '    public List<String> runes;',
          '    Scroll(List<String> runes) { this.runes = runes; }',
          '}',
        ]),
      },
      {
        id: 'b',
        label: j([
          'class Scroll {',
          '    private final List<String> runes;',
          '    Scroll(List<String> runes) { this.runes = runes; }',
          '    List<String> runes() { return runes; }',
          '}',
        ]),
      },
      {
        id: 'c',
        label: j([
          'class Scroll {',
          '    private final List<String> runes;',
          '    Scroll(List<String> runes) {',
          '        this.runes = new ArrayList<>(runes);',
          '    }',
          '    List<String> runes() {',
          '        return new ArrayList<>(runes);',
          '    }',
          '}',
        ]),
      },
      {
        id: 'd',
        label: j([
          'class Scroll {',
          '    private final List<String> runes = new ArrayList<>();',
          '    void add(String r) { runes.add(r); }',
          '}',
        ]),
      },
    ],
    correctId: 'c',
    hint: 'Copy on the way in and on the way out. Returning or storing the caller’s list leaves a mutable alias.',
    explanation:
      'A is public mutable state. B stores the caller’s list and returns it — callers can add after construction. D is a final field with a mutator. C copies the constructor argument so later caller mutations do not affect the Scroll, and the getter returns a fresh copy so callers cannot mutate internals. (List.copyOf would also work and would reject nulls.)',
    explanationSteps: [
      'private final is necessary but not sufficient if the list is shared.',
      'new ArrayList<>(runes) in the constructor takes a snapshot.',
      'Returning new ArrayList<>(runes) avoids leaking the field.',
      'A, B, and D all allow mutation after “construction.”',
    ],
    codexId: 'immutability',
    expectCompile: 'fail',
    fixMode: 'inject',
    fixMarker: '/*FIX*/',
    commonTrap: 'Picking B because the field is private final — that still shares the list.',
  },
]
