import type { Puzzle } from './types'
import { joinLines as j } from './types'

export const ZONE6_PUZZLES: Puzzle[] = [
  {
    id: 'z6-upcast',
    kind: 'compile_error',
    title: 'Silent Lift',
    prompt: 'Why does this fail?',
    code: j([
      'class Animal {',
      '    void eat() { System.out.println("eat"); }',
      '}',
      '',
      'class Dog extends Animal {',
      '    void bark() { System.out.println("bark"); }',
      '}',
      '',
      'public class Lift {',
      '    public static void main(String[] args) {',
      '        Animal a = new Dog();',
      '        a.bark();',
      '    }',
      '}',
    ]),
    choices: [
      {
        id: 'a',
        label:
          'a has compile-time type Animal, which has no bark(). Upcast limits the API you can call.',
      },
      { id: 'b', label: 'new Dog() is illegal when assigned to Animal.' },
      { id: 'c', label: 'bark must be static.' },
      { id: 'd', label: 'Animal cannot be a superclass.' },
    ],
    correctId: 'a',
    hint: 'Upcast is fine. Calling Dog-only methods on an Animal reference is not.',
    explanation:
      'Animal a = new Dog() is a legal upcast. The compiler only allows methods declared on Animal. Cast to Dog (after a check) to call bark().',
    explanationSteps: [
      'Upcast succeeds at compile time and runtime.',
      'a.bark() is checked against Animal.',
      'Animal has no bark → compile error.',
      '((Dog) a).bark() would compile (and run here).',
    ],
    codexId: 'z6',
    expectCompile: 'fail',
    commonTrap: 'Thinking the assignment Animal a = new Dog() itself is illegal.',
  },
  {
    id: 'z6-downcast',
    kind: 'runtime',
    title: 'Brittle Cast',
    prompt: 'What happens when main runs?',
    code: j([
      'class Animal {}',
      'class Dog extends Animal {}',
      'class Cat extends Animal {}',
      '',
      'public class Brittle {',
      '    public static void main(String[] args) {',
      '        Animal a = new Cat();',
      '        try {',
      '            Dog d = (Dog) a;',
      '            System.out.println("ok");',
      '        } catch (ClassCastException e) {',
      '            System.out.println("ClassCastException");',
      '        }',
      '    }',
      '}',
    ]),
    choices: [
      { id: 'a', label: 'ok' },
      { id: 'b', label: 'ClassCastException' },
      { id: 'c', label: 'Compile error' },
      { id: 'd', label: 'NullPointerException' },
    ],
    correctId: 'b',
    hint: 'The object is a Cat. Casting to Dog fails at runtime.',
    explanation:
      'The cast compiles because Animal might be a Dog. At runtime the object’s class is Cat, so (Dog) a throws ClassCastException. This program catches it and prints the name.',
    explanationSteps: [
      'a refers to a Cat.',
      '(Dog) a is allowed by the compiler.',
      'JVM checks the real type → not a Dog → ClassCastException.',
      'catch prints ClassCastException.',
    ],
    codexId: 'z6',
    expectCompile: 'ok',
    expectedOutput: 'ClassCastException',
    commonTrap: 'Expecting a compile error, or thinking the cast silently becomes null.',
  },
  {
    id: 'z6-instance',
    kind: 'output',
    title: 'Safe Gate',
    prompt: 'What does main print?',
    code: j([
      'class Animal {}',
      'class Dog extends Animal {',
      '    void bark() { System.out.println("bark"); }',
      '}',
      '',
      'public class Safe {',
      '    public static void main(String[] args) {',
      '        Animal a = new Dog();',
      '        if (a instanceof Dog) {',
      '            Dog d = (Dog) a;',
      '            d.bark();',
      '        } else {',
      '            System.out.println("no");',
      '        }',
      '    }',
      '}',
    ]),
    choices: [
      { id: 'a', label: 'no' },
      { id: 'b', label: 'bark' },
      { id: 'c', label: 'ClassCastException' },
      { id: 'd', label: 'Compile error' },
    ],
    correctId: 'b',
    hint: 'instanceof Dog is true, so the cast is safe.',
    explanation:
      'Guard with instanceof, then downcast. Here the object really is a Dog, so bark prints. (Pattern matching if (a instanceof Dog d) is the modern short form.)',
    explanationSteps: [
      'Runtime type of a is Dog.',
      'instanceof Dog succeeds.',
      'Cast succeeds.',
      'bark prints bark.',
    ],
    codexId: 'z6',
    expectCompile: 'ok',
    expectedOutput: 'bark',
    commonTrap: 'Expecting ClassCastException even after a successful instanceof check.',
  },
  {
    id: 'z6-super',
    kind: 'output',
    title: 'Parent Echo',
    prompt: 'What does new Child().speak() print?',
    code: j([
      'class Parent {',
      '    void speak() { System.out.println("parent"); }',
      '}',
      '',
      'class Child extends Parent {',
      '    @Override',
      '    void speak() {',
      '        super.speak();',
      '        System.out.println("child");',
      '    }',
      '}',
      '',
      'public class Echo {',
      '    public static void main(String[] args) {',
      '        new Child().speak();',
      '    }',
      '}',
    ]),
    choices: [
      { id: 'a', label: 'child\nparent' },
      { id: 'b', label: 'parent\nchild' },
      { id: 'c', label: 'child' },
      { id: 'd', label: 'parent' },
    ],
    correctId: 'b',
    hint: 'super.speak() runs Parent.speak first, then the rest of Child.speak.',
    explanation:
      'super.method() calls the superclass implementation without recursion into the override. Then Child prints child.',
    explanationSteps: [
      'Child.speak starts.',
      'super.speak() → parent.',
      'Then child.',
    ],
    codexId: 'z6',
    expectCompile: 'ok',
    expectedOutput: 'parent\nchild',
    commonTrap: 'Thinking super.speak() is illegal or infinite-loops.',
  },
  {
    id: 'z6-abstract',
    kind: 'compile_error',
    title: 'Obligation',
    prompt: 'Why is Circle illegal?',
    code: j([
      'abstract class Shape {',
      '    abstract double area();',
      '}',
      '',
      'class Circle extends Shape {',
      '    double r = 1;',
      '}',
    ]),
    choices: [
      {
        id: 'a',
        label:
          'Circle is concrete but does not implement abstract area(); it must implement it or be declared abstract.',
      },
      { id: 'b', label: 'Abstract classes cannot declare methods.' },
      { id: 'c', label: 'r must be final.' },
      { id: 'd', label: 'Circle must implement Cloneable.' },
    ],
    correctId: 'a',
    hint: 'Abstract methods are a contract for concrete subclasses.',
    explanation:
      'Shape.area() has no body. Any non-abstract subclass must provide area(). Making Circle abstract would also compile.',
    explanationSteps: [
      'Shape declares abstract area().',
      'Circle extends Shape and is not abstract.',
      'Circle does not implement area().',
      'Compile error.',
    ],
    codexId: 'z6',
    expectCompile: 'fail',
    commonTrap: 'Thinking abstract methods somehow get an empty default body.',
  },
  {
    id: 'z6-boss',
    kind: 'concept',
    title: 'Forge Heart',
    prompt:
      'You need shared fields in one IS-A family, plus a capability many unrelated types can adopt. Which design fits Java?',
    code: j([
      'public class Forge {',
      '    public static void main(String[] args) {',
      '        System.out.println("design");',
      '    }',
      '}',
    ]),
    choices: [
      {
        id: 'a',
        label:
          'Abstract class for shared IS-A + fields; interface for a capability many unrelated types can adopt.',
      },
      {
        id: 'b',
        label: 'Interfaces hold per-instance mutable fields like classes.',
      },
      {
        id: 'c',
        label: 'Never combine an abstract class with an interface.',
      },
      {
        id: 'd',
        label: 'Abstract class and interface are identical in Java.',
      },
    ],
    correctId: 'a',
    hint: 'One superclass, many interfaces. Interface fields are constants.',
    explanation:
      'Shared stateful hierarchy → abstract class. Cross-cutting capability → interface. You often use both: class Duck extends Bird implements Flyable.',
    explanationSteps: [
      'Single inheritance limits you to one extends.',
      'Interfaces add capabilities without that limit.',
      'Interface fields are public static final, not instance state.',
      'a is the exam-correct design rule.',
    ],
    codexId: 'z6',
    expectCompile: 'ok',
    commonTrap: 'Treating abstract class and interface as interchangeable.',
  },
]
