import type { Puzzle } from './types'
import { joinLines as j } from './types'

export const ZONE1_PUZZLES: Puzzle[] = [
  {
    id: 'z1-gate',
    kind: 'output',
    title: 'Gate of super()',
    prompt:
      'A Child is constructed. What does main print? Remember what a constructor does if you never write super().',
    code: j([
      'class Parent {',
      '    Parent() {',
      '        System.out.println("Parent");',
      '    }',
      '}',
      '',
      'class Child extends Parent {',
      '    Child() {',
      '        System.out.println("Child");',
      '    }',
      '}',
      '',
      'public class Gate {',
      '    public static void main(String[] args) {',
      '        new Child();',
      '    }',
      '}',
    ]),
    choices: [
      { id: 'a', label: 'Parent\nChild' },
      { id: 'b', label: 'Child\nParent' },
      { id: 'c', label: 'Child' },
      { id: 'd', label: 'Parent' },
    ],
    correctId: 'a',
    hint: 'If you do not write super() or this(), the compiler inserts super() as the first statement.',
    explanation:
      'Every constructor must start by chaining. Child() has no explicit super() or this(), so the compiler inserts super() — a call to Parent(). Parent prints first, then the rest of Child() runs.',
    explanationSteps: [
      'new Child() enters Child().',
      'The compiler inserted super() as the first statement, so Parent() runs.',
      'Parent() prints "Parent", then returns.',
      'Child() continues and prints "Child".',
    ],
    codexId: 'chaining',
    expectCompile: 'ok',
    expectedOutput: 'Parent\nChild',
    commonTrap: 'Predicting Child then Parent, as if the subclass constructor ran first.',
  },
  {
    id: 'z1-twin',
    kind: 'output',
    title: 'Twin Scrolls',
    prompt:
      'Child(int) chains to this(), and the no-arg Child constructor still has to reach Parent. What is the print order?',
    code: j([
      'class Parent {',
      '    Parent() {',
      '        System.out.println("keep");',
      '    }',
      '}',
      '',
      'class Child extends Parent {',
      '    Child() {',
      '        System.out.println("base");',
      '    }',
      '',
      '    Child(int n) {',
      '        this();',
      '        System.out.println("n=" + n);',
      '    }',
      '}',
      '',
      'public class TwinScrolls {',
      '    public static void main(String[] args) {',
      '        new Child(7);',
      '    }',
      '}',
    ]),
    choices: [
      { id: 'a', label: 'n=7\nbase\nkeep' },
      { id: 'b', label: 'keep\nbase\nn=7' },
      { id: 'c', label: 'base\nkeep\nn=7' },
      { id: 'd', label: 'keep\nn=7\nbase' },
    ],
    correctId: 'b',
    hint: 'this() must finish completely — including the implicit super() inside the target constructor — before the leftover body of Child(int) runs.',
    explanation:
      'Child(int) starts with this(), so it jumps to Child(). Child() does not write super(), so Parent() runs first. Only after that chain returns does Child(int) print n=7. You cannot call both this() and super() in the same constructor; this() borrows the other constructor’s super() call.',
    explanationSteps: [
      'new Child(7) enters Child(int).',
      'this() transfers to Child().',
      'Child() inserts super(), so Parent() prints "keep".',
      'Child() prints "base" and returns.',
      'Child(int) resumes and prints "n=7".',
    ],
    codexId: 'chaining',
    expectCompile: 'ok',
    expectedOutput: 'keep\nbase\nn=7',
    commonTrap: 'Printing n=7 before the this() chain (including Parent) has finished.',
  },
  {
    id: 'z1-dual',
    kind: 'compile_error',
    title: 'Broken Dual Call',
    prompt:
      'This class file does not compile. Which rule did the cursed constructor break?',
    code: j([
      'class Relic {',
      '    Relic(int power) {',
      '        System.out.println("charge " + power);',
      '    }',
      '}',
      '',
      'class CursedRelic extends Relic {',
      '    CursedRelic() {',
      '        super(1);',
      '        this(2);',
      '    }',
      '',
      '    CursedRelic(int n) {',
      '        super(n);',
      '    }',
      '}',
    ]),
    choices: [
      {
        id: 'a',
        label:
          'A constructor may call this() or super(), but not both — and the call must be the first statement.',
      },
      {
        id: 'b',
        label: 'A subclass is not allowed to declare two constructors.',
      },
      {
        id: 'c',
        label: 'super(1) is illegal because Relic already has an int constructor.',
      },
      {
        id: 'd',
        label: 'this(2) is illegal because CursedRelic(int) uses super(n).',
      },
    ],
    correctId: 'a',
    hint: 'Look at CursedRelic() — it tries to chain to the parent and to a sibling constructor.',
    explanation:
      'Java constructors are allowed one chaining call, and it must be the first statement. super(...) invokes the parent constructor; this(...) forwards to another constructor in the same class (which will eventually call super). Writing both is a compile error. Putting any statement before this() or super() is also a compile error.',
    explanationSteps: [
      'CursedRelic() begins with super(1), which is a legal parent call by itself.',
      'this(2) is a second constructor invocation in the same body — illegal.',
      'Even if you swapped the lines, this() would have to be first, and then super() would still be forbidden.',
      'CursedRelic(int) is fine on its own: one super(n) as the first statement.',
    ],
    codexId: 'chaining',
    expectCompile: 'fail',
    commonTrap: 'Thinking two constructors in a subclass are illegal, or that super(1) itself is the problem.',
  },
  {
    id: 'z1-specter',
    kind: 'output',
    title: 'Ghost of the Abstract',
    prompt:
      'Specter is abstract, but it still has a constructor. What happens when we construct a Wraith?',
    code: j([
      'abstract class Specter {',
      '    Specter() {',
      '        System.out.println("specter");',
      '    }',
      '}',
      '',
      'class Wraith extends Specter {',
      '    Wraith() {',
      '        System.out.println("wraith");',
      '    }',
      '}',
      '',
      'public class Summon {',
      '    public static void main(String[] args) {',
      '        Specter s = new Wraith();',
      '    }',
      '}',
    ]),
    choices: [
      { id: 'a', label: 'Compile error: abstract classes cannot have constructors.' },
      { id: 'b', label: 'Compile error: you cannot declare a variable of an abstract type.' },
      { id: 'c', label: 'specter\nwraith' },
      { id: 'd', label: 'wraith' },
    ],
    correctId: 'c',
    hint: 'abstract only blocks `new Specter()`. Subclass construction still walks the parent constructor.',
    explanation:
      'Abstract classes can (and often should) have constructors. You cannot write new Specter(), but new Wraith() is legal. Wraith() still calls super(), so Specter() runs and can set up shared state. Typing the variable as Specter is also legal — that is polymorphism, not instantiation of the abstract type.',
    explanationSteps: [
      'new Wraith() is allowed because Wraith is concrete.',
      'Wraith() inserts super(), which is Specter().',
      'Specter() prints "specter" even though Specter is abstract.',
      'Wraith() prints "wraith". The variable type Specter does not change construction order.',
    ],
    codexId: 'abstract-ctors',
    expectCompile: 'ok',
    expectedOutput: 'specter\nwraith',
    commonTrap: 'Calling this a compile error because Specter is abstract or because the variable type is Specter.',
  },
  {
    id: 'z1-ritual',
    kind: 'output',
    title: 'Init Ritual',
    prompt:
      'Field initializers and instance blocks run as part of construction. What is the exact print order for new Child()?',
    code: j([
      'class Parent {',
      '    int p = print("parent field");',
      '    {',
      '        System.out.println("parent block");',
      '    }',
      '    Parent() {',
      '        System.out.println("parent ctor");',
      '    }',
      '    static int print(String msg) {',
      '        System.out.println(msg);',
      '        return 0;',
      '    }',
      '}',
      '',
      'class Child extends Parent {',
      '    int c = print("child field");',
      '    {',
      '        System.out.println("child block");',
      '    }',
      '    Child() {',
      '        System.out.println("child ctor");',
      '    }',
      '}',
      '',
      'public class Ritual {',
      '    public static void main(String[] args) {',
      '        new Child();',
      '    }',
      '}',
    ]),
    choices: [
      {
        id: 'a',
        label:
          'parent field\nparent block\nparent ctor\nchild field\nchild block\nchild ctor',
      },
      {
        id: 'b',
        label:
          'parent ctor\nparent field\nparent block\nchild ctor\nchild field\nchild block',
      },
      {
        id: 'c',
        label:
          'parent field\nchild field\nparent block\nchild block\nparent ctor\nchild ctor',
      },
      {
        id: 'd',
        label:
          'child field\nchild block\nchild ctor\nparent field\nparent block\nparent ctor',
      },
    ],
    correctId: 'a',
    hint: 'Finish the whole parent object (its fields, blocks, then constructor body) before any child instance initializers run.',
    explanation:
      'After super() returns, Java runs that class’s instance field initializers and instance initializer blocks in source order, then the constructor body. So Parent is fully initialized before Child’s fields and blocks run. The print helper is just a static method used to make field initializers visible.',
    explanationSteps: [
      'Child() calls super() and enters Parent().',
      'Parent field initializers and the instance block run in source order: "parent field", then "parent block".',
      'Parent() body prints "parent ctor" and returns.',
      'Child field + block run: "child field", then "child block".',
      'Child() body prints "child ctor".',
    ],
    codexId: 'init-order',
    expectCompile: 'ok',
    expectedOutput:
      'parent field\nparent block\nparent ctor\nchild field\nchild block\nchild ctor',
    commonTrap: 'Running child fields/blocks before the parent constructor body returns.',
  },
  {
    id: 'z1-static',
    kind: 'output',
    title: 'Static vs Instance',
    prompt:
      'Static initializers belong to the class, not the object. What prints for a single new Tower()?',
    code: j([
      'class Keep {',
      '    static {',
      '        System.out.println("Keep static");',
      '    }',
      '    {',
      '        System.out.println("Keep instance");',
      '    }',
      '    Keep() {',
      '        System.out.println("Keep ctor");',
      '    }',
      '}',
      '',
      'class Tower extends Keep {',
      '    static {',
      '        System.out.println("Tower static");',
      '    }',
      '    {',
      '        System.out.println("Tower instance");',
      '    }',
      '    Tower() {',
      '        System.out.println("Tower ctor");',
      '    }',
      '}',
      '',
      'public class Watch {',
      '    public static void main(String[] args) {',
      '        new Tower();',
      '    }',
      '}',
    ]),
    choices: [
      {
        id: 'a',
        label:
          'Keep instance\nKeep ctor\nTower instance\nTower ctor\nKeep static\nTower static',
      },
      {
        id: 'b',
        label:
          'Tower static\nKeep static\nTower instance\nKeep instance\nTower ctor\nKeep ctor',
      },
      {
        id: 'c',
        label:
          'Keep static\nTower static\nKeep instance\nKeep ctor\nTower instance\nTower ctor',
      },
      {
        id: 'd',
        label:
          'Keep static\nKeep instance\nKeep ctor\nTower static\nTower instance\nTower ctor',
      },
    ],
    correctId: 'c',
    hint: 'Classes load superclass-first. Static blocks run once at load time, before any constructor.',
    explanation:
      'Using Tower for the first time loads Keep, then Tower. Each class runs its static initializers once, superclass first. Only then does construction follow the usual instance path: Keep instance block + ctor, then Tower instance block + ctor. A second new Tower() would skip both static lines and repeat only the instance/constructor lines.',
    explanationSteps: [
      'First use of Tower loads Keep, then Tower.',
      'Keep’s static block prints, then Tower’s static block prints.',
      'Construction of the object: Keep instance block, Keep ctor.',
      'Then Tower instance block, Tower ctor.',
      'Static work is not repeated for later instances.',
    ],
    codexId: 'init-order',
    expectCompile: 'ok',
    expectedOutput:
      'Keep static\nTower static\nKeep instance\nKeep ctor\nTower instance\nTower ctor',
    commonTrap: 'Running Tower’s static block before Keep’s, or mixing instance work into class-load time.',
  },
  {
    id: 'z1-leak',
    kind: 'output',
    title: 'The Leak',
    prompt:
      'The constructor publishes this before charge is assigned. What does the watcher print?',
    code: j([
      'class Archive {',
      '    static Rune leaked;',
      '}',
      '',
      'class Rune {',
      '    int charge;',
      '    Rune() {',
      '        Archive.leaked = this;',
      '        System.out.println(Archive.leaked.charge);',
      '        charge = 7;',
      '    }',
      '}',
      '',
      'public class Leak {',
      '    public static void main(String[] args) {',
      '        new Rune();',
      '    }',
      '}',
    ]),
    choices: [
      { id: 'a', label: '7' },
      { id: 'b', label: '0' },
      { id: 'c', label: 'NullPointerException' },
      { id: 'd', label: 'Compile error: cannot use this inside a constructor.' },
    ],
    correctId: 'b',
    hint: 'int fields start at 0. The assignment charge = 7 happens after the print.',
    explanation:
      'This is a leaked this: the object is shared with the outside world before construction finishes. int charge has the default 0 until the constructor body assigns 7. Archive.leaked is not null — it already points at the half-built Rune — so you get 0, not an exception. The same trap appears when a superclass constructor calls a method the subclass overrides; subclass fields are still at defaults.',
    explanationSteps: [
      'new Rune() allocates the object and default-initializes charge to 0.',
      'The constructor stores this in Archive.leaked — outsiders can now see the object.',
      'Printing leaked.charge reads 0 because charge = 7 has not run yet.',
      'Only then does charge become 7. Anyone who kept the leaked reference later would see 7.',
    ],
    codexId: 'leaking-this',
    expectCompile: 'ok',
    expectedOutput: '0',
    commonTrap: 'Printing 7, or expecting NullPointerException because construction is “not done.”',
  },
  {
    id: 'z1-heart-output',
    kind: 'output',
    title: 'Citadel Heart',
    prompt:
      'this() chaining plus instance blocks. Predict the full printout of new Heart().',
    code: j([
      'class Keep {',
      '    {',
      '        System.out.println("Keep block");',
      '    }',
      '    Keep() {',
      '        System.out.println("Keep ctor");',
      '    }',
      '    Keep(String s) {',
      '        this();',
      '        System.out.println(s);',
      '    }',
      '}',
      '',
      'class Heart extends Keep {',
      '    {',
      '        System.out.println("Heart block");',
      '    }',
      '    Heart() {',
      '        super("seal");',
      '        System.out.println("Heart ctor");',
      '    }',
      '}',
      '',
      'public class CitadelHeart {',
      '    public static void main(String[] args) {',
      '        new Heart();',
      '    }',
      '}',
    ]),
    choices: [
      {
        id: 'a',
        label: 'Heart block\nKeep block\nKeep ctor\nseal\nHeart ctor',
      },
      {
        id: 'b',
        label: 'Keep ctor\nKeep block\nseal\nHeart block\nHeart ctor',
      },
      {
        id: 'c',
        label: 'Keep block\nKeep ctor\nseal\nHeart block\nHeart ctor',
      },
      {
        id: 'd',
        label: 'Keep block\nKeep ctor\nHeart block\nHeart ctor\nseal',
      },
    ],
    correctId: 'c',
    hint: 'Keep(String) delegates with this(), so Keep’s instance block runs with Keep(), not twice. Heart’s block waits until super() returns.',
    explanation:
      'Heart() calls super("seal"), which is Keep(String). That constructor immediately this()-delegates to Keep(). Instance initializers of Keep run once, after Object() returns and before Keep()’s body. Then Keep(String) prints "seal". Only after the entire parent constructor chain finishes do Heart’s instance block and constructor body run.',
    explanationSteps: [
      'Heart() calls super("seal") → Keep(String).',
      'Keep(String) calls this() → Keep(), which calls Object().',
      'Keep’s instance block prints "Keep block", then Keep() prints "Keep ctor".',
      'Keep(String) resumes and prints "seal".',
      'Heart’s instance block prints "Heart block", then Heart() prints "Heart ctor".',
    ],
    codexId: 'init-order',
    expectCompile: 'ok',
    expectedOutput: 'Keep block\nKeep ctor\nseal\nHeart block\nHeart ctor',
    commonTrap: 'Running Heart’s instance block before Keep(String) finishes, or running Keep’s block after Keep().',
  },
  {
    id: 'z1-heart-fix',
    kind: 'fix',
    title: 'Vault Door',
    prompt:
      'Vault has no no-arg constructor. Which Door constructor actually compiles?',
    code: j([
      'class Vault {',
      '    Vault(int key) {',
      '        System.out.println("key " + key);',
      '    }',
      '}',
      '',
      'class Door extends Vault {',
      '    /*FIX*/',
      '}',
    ]),
    choices: [
      { id: 'a', label: 'Door() { }' },
      { id: 'b', label: 'Door() { super(); }' },
      { id: 'c', label: 'Door() { super(3); }' },
      { id: 'd', label: 'Door() { this(3); }' },
    ],
    correctId: 'c',
    hint: 'If the parent has no no-arg constructor, implicit super() cannot compile. this(3) needs a Door(int) that does not exist.',
    explanation:
      'A subclass constructor always chains. Door() { } and Door() { super(); } both try to call Vault(), which does not exist. Door() { this(3); } would need another Door constructor that takes an int. The legal fix is an explicit super(3) matching Vault(int). This is the same rule as the Gate: when the parent constructor is not a free no-arg, you must write the super(...) call yourself.',
    explanationSteps: [
      'Vault only declares Vault(int), so the compiler does not generate Vault().',
      'An empty Door() still inserts super() — compile error.',
      'super() written by hand has the same problem.',
      'this(3) is not a parent call; there is no Door(int) to forward to.',
      'super(3) matches Vault(int) and compiles.',
    ],
    codexId: 'chaining',
    expectCompile: 'fail',
    fixMode: 'inject',
    fixMarker: '/*FIX*/',
    commonTrap: 'Relying on an implicit super() when Vault has no no-arg constructor, or using this(3) with no Door(int).',
  },
]
