import type { Puzzle } from './types'
import { joinLines as j } from './types'

export const ZONE7_PUZZLES: Puzzle[] = [
  {
    id: 'z7-nested',
    kind: 'output',
    title: 'Inner / Nested',
    prompt: 'What does main print?',
    code: j([
      'class Outer {',
      '    private int n = 3;',
      '    static class Nested {',
      '        int read() { return 1; }',
      '    }',
      '    class Inner {',
      '        int read() { return n; }',
      '    }',
      '}',
      '',
      'public class Nest {',
      '    public static void main(String[] args) {',
      '        System.out.println(new Outer.Nested().read());',
      '        System.out.println(new Outer().new Inner().read());',
      '    }',
      '}',
    ]),
    choices: [
      { id: 'a', label: '1\n3' },
      { id: 'b', label: '3\n1' },
      { id: 'c', label: 'Compile error on Nested' },
      { id: 'd', label: 'Compile error on Inner' },
    ],
    correctId: 'a',
    hint: 'Static nested needs no Outer instance. Inner uses Outer.this.n.',
    explanation:
      'Outer.Nested is static — construct with new Outer.Nested(). Inner needs an Outer instance: new Outer().new Inner(). Inner can read private n.',
    explanationSteps: [
      'Nested.read returns 1.',
      'Inner is bound to an Outer whose n is 3.',
      'Print 1 then 3.',
    ],
    codexId: 'z7',
    expectCompile: 'ok',
    expectedOutput: '1\n3',
    wrongReasons: {
      b: '“3\\n1” is incorrect. Static nested needs no Outer instance. Inner uses Outer.this.n.',
      c: '“Compile error on Nested” is incorrect. Static nested needs no Outer instance. Inner uses Outer.this.n.',
      d: '“Compile error on Inner” is incorrect. Static nested needs no Outer instance. Inner uses Outer.this.n.',
    },
    commonTrap: 'Writing new Outer.Inner() without an Outer instance.',
  },
  {
    id: 'z7-enum',
    kind: 'output',
    title: 'Enum Court',
    prompt: 'What does main print?',
    code: j([
      'enum Suit { HEARTS, CLUBS }',
      '',
      'public class Court {',
      '    public static void main(String[] args) {',
      '        System.out.println(Suit.HEARTS.name());',
      '        System.out.println(Suit.values().length);',
      '    }',
      '}',
    ]),
    choices: [
      { id: 'a', label: 'HEARTS\n2' },
      { id: 'b', label: '0\n2' },
      { id: 'c', label: 'HEARTS\n1' },
      { id: 'd', label: 'Compile error' },
    ],
    correctId: 'a',
    hint: 'name() is the constant id; values() lists all constants.',
    explanation:
      'Enums are typesafe constants. name() returns "HEARTS". values() returns both HEARTS and CLUBS (length 2).',
    explanationSteps: [
      'Suit.HEARTS.name() → HEARTS.',
      'Suit.values() has two entries.',
      'Print HEARTS then 2.',
    ],
    codexId: 'z7',
    expectCompile: 'ok',
    expectedOutput: 'HEARTS\n2',
    wrongReasons: {
      b: '“0\\n2” is incorrect. name() is the constant id; values() lists all constants.',
      c: '“HEARTS\\n1” is incorrect. name() is the constant id; values() lists all constants.',
      d: '“Compile error” is incorrect. name() is the constant id; values() lists all constants.',
    },
    commonTrap: 'Treating the enum as its ordinal 0 in name().',
  },
  {
    id: 'z7-record',
    kind: 'output',
    title: 'Record Shelf',
    prompt: 'What does main print? (Java 16+ records)',
    code: j([
      'record Point(int x, int y) {}',
      '',
      'public class Shelf {',
      '    public static void main(String[] args) {',
      '        Point p = new Point(2, 5);',
      '        System.out.println(p.x() + "," + p.y());',
      '    }',
      '}',
    ]),
    choices: [
      { id: 'a', label: '2,5' },
      { id: 'b', label: 'Compile error: no getters' },
      { id: 'c', label: '0,0' },
      { id: 'd', label: 'Point@hash' },
    ],
    correctId: 'a',
    hint: 'Records generate accessors named like the components: x(), y().',
    explanation:
      'record Point(int x, int y) creates a final class with a canonical constructor and accessors x() and y(). Fields are private final.',
    explanationSteps: [
      'new Point(2, 5) stores components.',
      'p.x() and p.y() are the generated accessors.',
      'Print 2,5.',
    ],
    codexId: 'z7',
    expectCompile: 'ok',
    expectedOutput: '2,5',
    wrongReasons: {
      b: '“Compile error: no getters” is incorrect. Records generate accessors named like the components: x(), y().',
      c: '“0,0” is incorrect. Records generate accessors named like the components: x(), y().',
      d: '“Point@hash” is incorrect. Records generate accessors named like the components: x(), y().',
    },
    commonTrap: 'Looking for getX() JavaBean names — records use x().',
  },
  {
    id: 'z7-tostring',
    kind: 'output',
    title: 'Name Plate',
    prompt: 'What does main print?',
    code: j([
      'class Coin {',
      '    int id;',
      '    Coin(int id) { this.id = id; }',
      '    @Override',
      '    public String toString() {',
      '        return "Coin(" + id + ")";',
      '    }',
      '}',
      '',
      'public class Plate {',
      '    public static void main(String[] args) {',
      '        System.out.println(new Coin(7));',
      '    }',
      '}',
    ]),
    choices: [
      { id: 'a', label: 'Coin@something' },
      { id: 'b', label: 'Coin(7)' },
      { id: 'c', label: '7' },
      { id: 'd', label: 'Compile error' },
    ],
    correctId: 'b',
    hint: 'println calls toString() on the object.',
    explanation:
      'Object’s default toString is Class@hexHash. Override toString for readable output. println uses that override.',
    explanationSteps: [
      'new Coin(7) created.',
      'println → toString().',
      'Override returns Coin(7).',
    ],
    codexId: 'z7',
    expectCompile: 'ok',
    expectedOutput: 'Coin(7)',
    wrongReasons: {
      a: '“Coin@something” is incorrect. println calls toString() on the object.',
      c: '“7” is incorrect. println calls toString() on the object.',
      d: '“Compile error” is incorrect. println calls toString() on the object.',
    },
    commonTrap: 'Expecting the default Class@hash form after an override exists.',
  },
  {
    id: 'z7-getclass',
    kind: 'output',
    title: 'Exact Mirror',
    prompt: 'What does main print?',
    code: j([
      'class Animal {}',
      'class Dog extends Animal {}',
      '',
      'public class Mirror {',
      '    public static void main(String[] args) {',
      '        Animal a = new Dog();',
      '        System.out.println(a instanceof Animal);',
      '        System.out.println(a.getClass() == Animal.class);',
      '        System.out.println(a.getClass() == Dog.class);',
      '    }',
      '}',
    ]),
    choices: [
      { id: 'a', label: 'true\ntrue\ntrue' },
      { id: 'b', label: 'true\nfalse\ntrue' },
      { id: 'c', label: 'false\nfalse\ntrue' },
      { id: 'd', label: 'true\ntrue\nfalse' },
    ],
    correctId: 'b',
    hint: 'instanceof allows subtypes. getClass() is the exact runtime class.',
    explanation:
      'a is a Dog, so instanceof Animal is true. getClass() returns Dog.class, not Animal.class.',
    explanationSteps: [
      'instanceof Animal → true (Dog is an Animal).',
      'getClass() == Animal.class → false.',
      'getClass() == Dog.class → true.',
    ],
    codexId: 'z7',
    expectCompile: 'ok',
    expectedOutput: 'true\nfalse\ntrue',
    wrongReasons: {
      a: '“true\\ntrue\\ntrue” is incorrect. instanceof allows subtypes. getClass() is the exact runtime class.',
      c: '“false\\nfalse\\ntrue” is incorrect. instanceof allows subtypes. getClass() is the exact runtime class.',
      d: '“true\\ntrue\\nfalse” is incorrect. instanceof allows subtypes. getClass() is the exact runtime class.',
    },
    commonTrap: 'Thinking getClass() == Animal.class because the variable type is Animal.',
  },
  {
    id: 'z7-boss',
    kind: 'fix',
    title: 'Object Hall',
    prompt: 'Which snippet compiles and prints HEARTS?',
    code: j([
      '/*FIX*/',
      '',
      'public class Hall {',
      '    public static void main(String[] args) {',
      '        System.out.println(Suit.HEARTS.name());',
      '    }',
      '}',
    ]),
    choices: [
      { id: 'a', label: 'class Suit { static String HEARTS = "HEARTS"; }' },
      { id: 'b', label: 'enum Suit { HEARTS, CLUBS }' },
      { id: 'c', label: 'interface Suit { String HEARTS = "HEARTS"; }' },
      { id: 'd', label: 'record Suit(String HEARTS) {}' },
    ],
    correctId: 'b',
    hint: 'name() is an Enum method. A String constant has no name().',
    explanation:
      'Only enum constants have name(). A static String field would use Suit.HEARTS without .name(). An interface constant is also a String. A record is a different type.',
    explanationSteps: [
      'Suit.HEARTS.name() requires Suit to be an enum.',
      'enum Suit { HEARTS, CLUBS } provides that.',
      'Other options do not define Enum.name().',
    ],
    codexId: 'z7',
    expectCompile: 'fail',
    fixMode: 'inject',
    fixMarker: '/*FIX*/',
    wrongReasons: {
      a: '“class Suit { static String HEARTS = "HEARTS"; }” is incorrect. name() is an Enum method. A String constant has no name().',
      c: '“interface Suit { String HEARTS = "HEARTS"; }” is incorrect. name() is an Enum method. A String constant has no name().',
      d: '“record Suit(String HEARTS) {}” is incorrect. name() is an Enum method. A String constant has no name().',
    },
    commonTrap: 'Using a String constant and still calling .name().',
  },
]
