import type { Room } from './rooms'

export const ZONE1_ROOMS: Room[] = [
  {
    id: 'gate',
    name: 'Gate of super()',
    topic: 'Constructor chaining',
    enemyId: 'gate-warden',
    puzzleIds: ['z1-gate'],
    requires: [],
    x: 50,
    y: 6,
  },
  {
    id: 'twin',
    name: 'Twin Scrolls',
    topic: 'this() overload chaining',
    enemyId: 'twin-scribe',
    puzzleIds: ['z1-twin'],
    requires: ['gate'],
    x: 50,
    y: 20,
  },
  {
    id: 'dual',
    name: 'Broken Dual Call',
    topic: 'Illegal this() + super()',
    enemyId: 'dual-hexer',
    puzzleIds: ['z1-dual'],
    requires: ['twin'],
    x: 24,
    y: 36,
  },
  {
    id: 'specter',
    name: 'Ghost of the Abstract',
    topic: 'Abstract class constructors',
    enemyId: 'specter',
    puzzleIds: ['z1-specter'],
    requires: ['twin'],
    x: 76,
    y: 36,
  },
  {
    id: 'ritual',
    name: 'Init Ritual',
    topic: 'Fields, blocks, constructors',
    enemyId: 'ritualist',
    puzzleIds: ['z1-ritual'],
    requires: ['dual', 'specter'],
    x: 50,
    y: 52,
  },
  {
    id: 'static',
    name: 'Static Sentinel',
    topic: 'Static vs instance init',
    enemyId: 'sentinel',
    puzzleIds: ['z1-static'],
    requires: ['ritual'],
    x: 50,
    y: 66,
  },
  {
    id: 'leak',
    name: 'The Leak',
    topic: 'Publishing this too early',
    enemyId: 'leaker',
    puzzleIds: ['z1-leak'],
    requires: ['static'],
    x: 50,
    y: 80,
  },
  {
    id: 'heart',
    name: 'Citadel Heart',
    topic: 'Chaining + init, then a fix',
    enemyId: 'heart',
    puzzleIds: ['z1-heart-output', 'z1-heart-fix'],
    requires: ['leak'],
    x: 50,
    y: 91,
    isBoss: true,
  },
]

export const ZONE1_EDGES: Array<[string, string]> = [
  ['gate', 'twin'],
  ['twin', 'dual'],
  ['twin', 'specter'],
  ['dual', 'ritual'],
  ['specter', 'ritual'],
  ['ritual', 'static'],
  ['static', 'leak'],
  ['leak', 'heart'],
]
